# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20171014_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='body',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
